[package]
name = "server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
futures = "0.3.30"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
tokio = { version = "1.39.2", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4"] }
